<a href="https://colab.research.google.com/github/nurfnick/SMaRT2023/blob/main/Code/StartedCleaningData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pa

data = pa.read_csv('https://data.cdc.gov/api/views/jr58-6ysp/rows.csv')

data.head()

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
0,USA,05/08/2021 12:00:00 AM,B.1.1.529,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM
1,USA,05/08/2021 12:00:00 AM,B.1.617.2,0.017526,0.021864,0.01385,0.0,weighted,weekly,03/31/2023 12:00:00 AM
2,USA,05/08/2021 12:00:00 AM,BA.1.1,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM
3,USA,05/08/2021 12:00:00 AM,BA.2,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM
4,USA,05/08/2021 12:00:00 AM,BA.2.12.1,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM

In [5]:
data.size/10

895799.0

In [9]:
data.share_hi.isna()

0          True
1         False
2          True
3          True
4          True
          ...
895794     True
895795     True
895796    False
895797    False
895798    False
Name: share_hi, Length: 895799, dtype: bool

In [14]:
data[(data.share>0.005)]

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
1,USA,05/08/2021 12:00:00 AM,B.1.617.2,0.017526,0.021864,0.013850,0.0,weighted,weekly,03/31/2023 12:00:00 AM
17,USA,05/08/2021 12:00:00 AM,Other,0.982474,0.986150,0.978136,0.0,weighted,weekly,03/31/2023 12:00:00 AM
23,USA,05/15/2021 12:00:00 AM,B.1.617.2,0.024116,0.030616,0.018674,0.0,weighted,weekly,03/31/2023 12:00:00 AM
39,USA,05/15/2021 12:00:00 AM,Other,0.975641,0.981130,0.969087,0.0,weighted,weekly,03/31/2023 12:00:00 AM
45,USA,05/22/2021 12:00:00 AM,B.1.617.2,0.039099,0.048710,0.030917,0.0,weighted,weekly,03/31/2023 12:00:00 AM
...,...,...,...,...,...,...,...,...,...,...
895791,10,07/17/2021 12:00:00 AM,B.1.617.2,0.695045,0.847142,0.483823,0.0,weighted,biweekly,08/03/2021 12:00:00 AM
895793,10,07/17/2021 12:00:00 AM,B.1.621,0.026704,0.112295,0.005915,0.0,weighted,biweekly,08/03/2021 12:00:00 AM
895796,10,07/17/2021 12:00:00 AM,B.1.628,0.006151,0.064837,0.000552,1.0,weighted,biweekly,08/03/2021 12:00:00 AM
895797,10,07/17/2021 12:00:00 AM,P.1,0.028198,0.199085,0.003376,0.0,weighted,biweekly,08/03/2021 12:00:00 AM
895798,10,07/17/2021 12:00:00 AM,Other,0.027404,0.088982,0.008063,1.0,weighted,biweekly,08/03/2021 12:00:00 AM

In [22]:
data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.2') & (data.week_ending == data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.2') & (data.share >0.005)].week_ending.min())]

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
2610,USA,01/07/2023 12:00:00 AM,BA.2,0.004095,0.006189,0.002571,0.0,weighted,weekly,03/31/2023 12:00:00 AM
21892,USA,01/07/2023 12:00:00 AM,BA.2,0.004799,0.007777,0.002747,0.0,weighted,weekly,01/27/2023 12:00:00 AM
72963,USA,01/07/2023 12:00:00 AM,BA.2,0.004090,0.005817,0.002771,0.0,weighted,biweekly,06/23/2023 12:00:00 AM
151652,USA,01/07/2023 12:00:00 AM,BA.2,0.004015,0.006026,0.002543,0.0,weighted,weekly,03/17/2023 12:00:00 AM
155072,USA,01/07/2023 12:00:00 AM,BA.2,0.003287,0.005052,0.002019,0.0,weighted,weekly,04/28/2023 12:00:00 AM
169147,USA,01/07/2023 12:00:00 AM,BA.2,0.004088,0.006181,0.002565,0.0,weighted,weekly,04/07/2023 12:00:00 AM
177701,USA,01/07/2023 12:00:00 AM,BA.2,0.004052,0.006100,0.002556,0.0,weighted,weekly,03/24/2023 12:00:00 AM
178638,USA,01/07/2023 12:00:00 AM,BA.2,0.004022,0.006032,0.002550,0.0,weighted,weekly,03/10/2023 12:00:00 AM
192045,USA,01/07/2023 12:00:00 AM,BA.2,0.003994,0.006027,0.002512,0.0,weighted,weekly,03/03/2023 12:00:00 AM
223374,USA,01/07/2023 12:00:00 AM,BA.2,0.004700,0.007031,0.002989,0.0,weighted,weekly,02/10/2023 12:00:00 AM
224946,USA,01/07/2023 12:00:00 AM,BA.2,0.003319,0.005427,0.001999,NaN,smoothed,weekly,01/13/2023 12:00:00 AM
280503,USA,01/07/2023 12:00:00 AM,BA.2,0.004113,0.005843,0.002791,0.0,weighted,biweekly,05/26/2023 12:00:00 AM
283430,USA,01/07/2023 12:00:00 AM,BA.2,0.003288,0.005033,0.002030,0.0,weighted,weekly,05/05/2023 12:00:00 AM
290254,USA,01/07/2023 12:00:00 AM,BA.2,0.004306,0.006492,0.002711,0.0,weighted,weekly,02/24/2023 12:00:00 AM
357148,USA,01/07/2023 12:00:00 AM,BA.2,0.004452,0.006689,0.002815,0.0,weighted,weekly,02/17/2023 12:00:00 AM
383038,USA,01/07/2023 12:00:00 AM,BA.2,0.003114,0.005282,0.001801,NaN,smoothed,weekly,01/06/2023 12:00:00 AM
472130,USA,01/07/2023 12:00:00 AM,BA.2,0.003288,0.005054,0.002020,0.0,weighted,weekly,04/21/2023 12:00:00 AM
583543,USA,01/07/2023 12:00:00 AM,BA.2,0.003301,0.005079,0.002026,0.0,weighted,weekly,04/14/2023 12:00:00 AM
617378,USA,01/07/2023 12:00:00 AM,BA.2,0.004108,0.005828,0.002792,0.0,weighted,biweekly,05/12/2023 12:00:00 AM
626695,USA,01/07/2023 12:00:00 AM,BA.2,0.003380,0.005038,0.002248,NaN,smoothed,weekly,01/20/2023 12:00:00 AM
699920,USA,01/07/2023 12:00:00 AM,BA.2,0.004098,0.005826,0.002777,0.0,weighted,biweekly,06/09/2023 12:00:00 AM
710395,USA,01/07/2023 12:00:00 AM,BA.2,0.005287,0.007772,0.003437,0.0,weighted,weekly,02/03/2023 12:00:00 AM