<a href="https://colab.research.google.com/github/nurfnick/SMaRT2023/blob/main/Code/StartedCleaningData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pa

data = pa.read_csv('https://data.cdc.gov/api/views/jr58-6ysp/rows.csv')

data.head()

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
0,USA,05/08/2021 12:00:00 AM,B.1.1.529,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM
1,USA,05/08/2021 12:00:00 AM,B.1.617.2,0.017526,0.021864,0.01385,0.0,weighted,weekly,03/31/2023 12:00:00 AM
2,USA,05/08/2021 12:00:00 AM,BA.1.1,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM
3,USA,05/08/2021 12:00:00 AM,BA.2,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM
4,USA,05/08/2021 12:00:00 AM,BA.2.12.1,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM

In [2]:
data.size/10

895799.0

In [3]:
data.share_hi.isna()

0          True
1         False
2          True
3          True
4          True
          ...
895794     True
895795     True
895796    False
895797    False
895798    False
Name: share_hi, Length: 895799, dtype: bool

In [4]:
data[(data.share>0.005)]

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
1,USA,05/08/2021 12:00:00 AM,B.1.617.2,0.017526,0.021864,0.013850,0.0,weighted,weekly,03/31/2023 12:00:00 AM
17,USA,05/08/2021 12:00:00 AM,Other,0.982474,0.986150,0.978136,0.0,weighted,weekly,03/31/2023 12:00:00 AM
23,USA,05/15/2021 12:00:00 AM,B.1.617.2,0.024116,0.030616,0.018674,0.0,weighted,weekly,03/31/2023 12:00:00 AM
39,USA,05/15/2021 12:00:00 AM,Other,0.975641,0.981130,0.969087,0.0,weighted,weekly,03/31/2023 12:00:00 AM
45,USA,05/22/2021 12:00:00 AM,B.1.617.2,0.039099,0.048710,0.030917,0.0,weighted,weekly,03/31/2023 12:00:00 AM
...,...,...,...,...,...,...,...,...,...,...
895791,10,07/17/2021 12:00:00 AM,B.1.617.2,0.695045,0.847142,0.483823,0.0,weighted,biweekly,08/03/2021 12:00:00 AM
895793,10,07/17/2021 12:00:00 AM,B.1.621,0.026704,0.112295,0.005915,0.0,weighted,biweekly,08/03/2021 12:00:00 AM
895796,10,07/17/2021 12:00:00 AM,B.1.628,0.006151,0.064837,0.000552,1.0,weighted,biweekly,08/03/2021 12:00:00 AM
895797,10,07/17/2021 12:00:00 AM,P.1,0.028198,0.199085,0.003376,0.0,weighted,biweekly,08/03/2021 12:00:00 AM
895798,10,07/17/2021 12:00:00 AM,Other,0.027404,0.088982,0.008063,1.0,weighted,biweekly,08/03/2021 12:00:00 AM

In [5]:
data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.2') & (data.week_ending == data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.2') & (data.share >0.005)].week_ending.min())]

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date
2610,USA,01/07/2023 12:00:00 AM,BA.2,0.004095,0.006189,0.002571,0.0,weighted,weekly,03/31/2023 12:00:00 AM
21892,USA,01/07/2023 12:00:00 AM,BA.2,0.004799,0.007777,0.002747,0.0,weighted,weekly,01/27/2023 12:00:00 AM
72963,USA,01/07/2023 12:00:00 AM,BA.2,0.004090,0.005817,0.002771,0.0,weighted,biweekly,06/23/2023 12:00:00 AM
151652,USA,01/07/2023 12:00:00 AM,BA.2,0.004015,0.006026,0.002543,0.0,weighted,weekly,03/17/2023 12:00:00 AM
155072,USA,01/07/2023 12:00:00 AM,BA.2,0.003287,0.005052,0.002019,0.0,weighted,weekly,04/28/2023 12:00:00 AM
169147,USA,01/07/2023 12:00:00 AM,BA.2,0.004088,0.006181,0.002565,0.0,weighted,weekly,04/07/2023 12:00:00 AM
177701,USA,01/07/2023 12:00:00 AM,BA.2,0.004052,0.006100,0.002556,0.0,weighted,weekly,03/24/2023 12:00:00 AM
178638,USA,01/07/2023 12:00:00 AM,BA.2,0.004022,0.006032,0.002550,0.0,weighted,weekly,03/10/2023 12:00:00 AM
192045,USA,01/07/2023 12:00:00 AM,BA.2,0.003994,0.006027,0.002512,0.0,weighted,weekly,03/03/2023 12:00:00 AM
223374,USA,01/07/2023 12:00:00 AM,BA.2,0.004700,0.007031,0.002989,0.0,weighted,weekly,02/10/2023 12:00:00 AM
224946,USA,01/07/2023 12:00:00 AM,BA.2,0.003319,0.005427,0.001999,NaN,smoothed,weekly,01/13/2023 12:00:00 AM
280503,USA,01/07/2023 12:00:00 AM,BA.2,0.004113,0.005843,0.002791,0.0,weighted,biweekly,05/26/2023 12:00:00 AM
283430,USA,01/07/2023 12:00:00 AM,BA.2,0.003288,0.005033,0.002030,0.0,weighted,weekly,05/05/2023 12:00:00 AM
290254,USA,01/07/2023 12:00:00 AM,BA.2,0.004306,0.006492,0.002711,0.0,weighted,weekly,02/24/2023 12:00:00 AM
357148,USA,01/07/2023 12:00:00 AM,BA.2,0.004452,0.006689,0.002815,0.0,weighted,weekly,02/17/2023 12:00:00 AM
383038,USA,01/07/2023 12:00:00 AM,BA.2,0.003114,0.005282,0.001801,NaN,smoothed,weekly,01/06/2023 12:00:00 AM
472130,USA,01/07/2023 12:00:00 AM,BA.2,0.003288,0.005054,0.002020,0.0,weighted,weekly,04/21/2023 12:00:00 AM
583543,USA,01/07/2023 12:00:00 AM,BA.2,0.003301,0.005079,0.002026,0.0,weighted,weekly,04/14/2023 12:00:00 AM
617378,USA,01/07/2023 12:00:00 AM,BA.2,0.004108,0.005828,0.002792,0.0,weighted,biweekly,05/12/2023 12:00:00 AM
626695,USA,01/07/2023 12:00:00 AM,BA.2,0.003380,0.005038,0.002248,NaN,smoothed,weekly,01/20/2023 12:00:00 AM
699920,USA,01/07/2023 12:00:00 AM,BA.2,0.004098,0.005826,0.002777,0.0,weighted,biweekly,06/09/2023 12:00:00 AM
710395,USA,01/07/2023 12:00:00 AM,BA.2,0.005287,0.007772,0.003437,0.0,weighted,weekly,02/03/2023 12:00:00 AM

In [6]:
data['variant_emerges'] = 0

In [7]:
data.head()

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date,variant_emerges
0,USA,05/08/2021 12:00:00 AM,B.1.1.529,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM,0
1,USA,05/08/2021 12:00:00 AM,B.1.617.2,0.017526,0.021864,0.01385,0.0,weighted,weekly,03/31/2023 12:00:00 AM,0
2,USA,05/08/2021 12:00:00 AM,BA.1.1,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM,0
3,USA,05/08/2021 12:00:00 AM,BA.2,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM,0
4,USA,05/08/2021 12:00:00 AM,BA.2.12.1,0.000000,NaN,NaN,1.0,weighted,weekly,03/31/2023 12:00:00 AM,0

I am just going to rid ourselves of all the data that is not nationwide.

In [8]:
data = data[data.usa_or_hhsregion == 'USA']

In [9]:
variants = data.variant.unique()
threshold = 0.005

In [10]:
for var in variants:
  data.loc[(data.variant == var) & (data.week_ending == data[ (data.variant == var) & (data.share > threshold)].week_ending.min()),'variant_emerges'] = 1

Most of the work is done in that `for` loop.  I think this works...

In [11]:
data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.2') & (data.week_ending == data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.2') & (data.share >0.005)].week_ending.min())]

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date,variant_emerges
2610,USA,01/07/2023 12:00:00 AM,BA.2,0.004095,0.006189,0.002571,0.0,weighted,weekly,03/31/2023 12:00:00 AM,1
21892,USA,01/07/2023 12:00:00 AM,BA.2,0.004799,0.007777,0.002747,0.0,weighted,weekly,01/27/2023 12:00:00 AM,1
72963,USA,01/07/2023 12:00:00 AM,BA.2,0.004090,0.005817,0.002771,0.0,weighted,biweekly,06/23/2023 12:00:00 AM,1
151652,USA,01/07/2023 12:00:00 AM,BA.2,0.004015,0.006026,0.002543,0.0,weighted,weekly,03/17/2023 12:00:00 AM,1
155072,USA,01/07/2023 12:00:00 AM,BA.2,0.003287,0.005052,0.002019,0.0,weighted,weekly,04/28/2023 12:00:00 AM,1
169147,USA,01/07/2023 12:00:00 AM,BA.2,0.004088,0.006181,0.002565,0.0,weighted,weekly,04/07/2023 12:00:00 AM,1
177701,USA,01/07/2023 12:00:00 AM,BA.2,0.004052,0.006100,0.002556,0.0,weighted,weekly,03/24/2023 12:00:00 AM,1
178638,USA,01/07/2023 12:00:00 AM,BA.2,0.004022,0.006032,0.002550,0.0,weighted,weekly,03/10/2023 12:00:00 AM,1
192045,USA,01/07/2023 12:00:00 AM,BA.2,0.003994,0.006027,0.002512,0.0,weighted,weekly,03/03/2023 12:00:00 AM,1
223374,USA,01/07/2023 12:00:00 AM,BA.2,0.004700,0.007031,0.002989,0.0,weighted,weekly,02/10/2023 12:00:00 AM,1
224946,USA,01/07/2023 12:00:00 AM,BA.2,0.003319,0.005427,0.001999,NaN,smoothed,weekly,01/13/2023 12:00:00 AM,1
280503,USA,01/07/2023 12:00:00 AM,BA.2,0.004113,0.005843,0.002791,0.0,weighted,biweekly,05/26/2023 12:00:00 AM,1
283430,USA,01/07/2023 12:00:00 AM,BA.2,0.003288,0.005033,0.002030,0.0,weighted,weekly,05/05/2023 12:00:00 AM,1
290254,USA,01/07/2023 12:00:00 AM,BA.2,0.004306,0.006492,0.002711,0.0,weighted,weekly,02/24/2023 12:00:00 AM,1
357148,USA,01/07/2023 12:00:00 AM,BA.2,0.004452,0.006689,0.002815,0.0,weighted,weekly,02/17/2023 12:00:00 AM,1
383038,USA,01/07/2023 12:00:00 AM,BA.2,0.003114,0.005282,0.001801,NaN,smoothed,weekly,01/06/2023 12:00:00 AM,1
472130,USA,01/07/2023 12:00:00 AM,BA.2,0.003288,0.005054,0.002020,0.0,weighted,weekly,04/21/2023 12:00:00 AM,1
583543,USA,01/07/2023 12:00:00 AM,BA.2,0.003301,0.005079,0.002026,0.0,weighted,weekly,04/14/2023 12:00:00 AM,1
617378,USA,01/07/2023 12:00:00 AM,BA.2,0.004108,0.005828,0.002792,0.0,weighted,biweekly,05/12/2023 12:00:00 AM,1
626695,USA,01/07/2023 12:00:00 AM,BA.2,0.003380,0.005038,0.002248,NaN,smoothed,weekly,01/20/2023 12:00:00 AM,1
699920,USA,01/07/2023 12:00:00 AM,BA.2,0.004098,0.005826,0.002777,0.0,weighted,biweekly,06/09/2023 12:00:00 AM,1
710395,USA,01/07/2023 12:00:00 AM,BA.2,0.005287,0.007772,0.003437,0.0,weighted,weekly,02/03/2023 12:00:00 AM,1

In [12]:
data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.1.1') & (data.week_ending == data[(data.usa_or_hhsregion == 'USA') & (data.variant == 'BA.1.1') & (data.share >0.005)].week_ending.min())]

,usa_or_hhsregion,week_ending,variant,share,share_hi,share_lo,nchs_or_count_flag,modeltype,time_interval,published_date,variant_emerges
750,USA,01/01/2022 12:00:00 AM,BA.1.1,0.425798,0.461154,0.390999,0.0,weighted,weekly,03/31/2023 12:00:00 AM,1
8169,USA,01/01/2022 12:00:00 AM,BA.1.1,0.456790,0.493415,0.420509,0.0,weighted,weekly,08/19/2022 12:00:00 AM,1
10387,USA,01/01/2022 12:00:00 AM,BA.1.1,0.456797,0.493591,0.420352,0.0,weighted,weekly,10/21/2022 12:00:00 AM,1
15711,USA,01/01/2022 12:00:00 AM,BA.1.1,0.455697,0.491955,0.419785,0.0,weighted,weekly,01/27/2023 12:00:00 AM,1
16701,USA,01/01/2022 12:00:00 AM,BA.1.1,0.456287,0.492662,0.420257,0.0,weighted,weekly,01/20/2023 12:00:00 AM,1
...,...,...,...,...,...,...,...,...,...,...,...
865294,USA,01/01/2022 12:00:00 AM,BA.1.1,0.459092,0.495867,0.422646,0.0,weighted,weekly,09/09/2022 12:00:00 AM,1
866318,USA,01/01/2022 12:00:00 AM,BA.1.1,0.454511,0.490947,0.418434,0.0,weighted,weekly,08/09/2022 12:00:00 AM,1
867575,USA,01/01/2022 12:00:00 AM,BA.1.1,0.454612,0.491059,0.418524,0.0,weighted,weekly,07/26/2022 12:00:00 AM,1
871671,USA,01/01/2022 12:00:00 AM,BA.1.1,0.445624,0.481477,0.410187,0.0,weighted,weekly,07/12/2022 12:00:00 AM,1
880005,USA,01/01/2022 12:00:00 AM,BA.1.1,0.434692,0.480221,0.389968,0.0,weighted,weekly,02/22/2022 12:00:00 AM,1

In [17]:
data = pa.get_dummies(data, columns = ['variant','modeltype','time_interval'])

In [18]:
data

,usa_or_hhsregion,week_ending,share,share_hi,share_lo,nchs_or_count_flag,time_interval,published_date,variant_emerges,variant_A.2.5,...,variant_XBB.1.16.1,variant_XBB.1.5,variant_XBB.1.5.1,variant_XBB.1.5.10,variant_XBB.1.5.68,variant_XBB.1.9.1,variant_XBB.1.9.2,variant_XBB.2.3,modeltype_smoothed,modeltype_weighted
0,USA,05/08/2021 12:00:00 AM,0.000000,NaN,NaN,1.0,weekly,03/31/2023 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
1,USA,05/08/2021 12:00:00 AM,0.017526,0.021864,0.013850,0.0,weekly,03/31/2023 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
2,USA,05/08/2021 12:00:00 AM,0.000000,NaN,NaN,1.0,weekly,03/31/2023 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
3,USA,05/08/2021 12:00:00 AM,0.000000,NaN,NaN,1.0,weekly,03/31/2023 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
4,USA,05/08/2021 12:00:00 AM,0.000000,NaN,NaN,1.0,weekly,03/31/2023 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884402,USA,07/17/2021 12:00:00 AM,0.005597,0.007932,0.003947,0.0,biweekly,08/03/2021 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
884403,USA,07/17/2021 12:00:00 AM,0.000000,NaN,NaN,1.0,biweekly,08/03/2021 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
884404,USA,07/17/2021 12:00:00 AM,0.004961,0.009697,0.002532,0.0,biweekly,08/03/2021 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
884405,USA,07/17/2021 12:00:00 AM,0.031412,0.043839,0.022425,0.0,biweekly,08/03/2021 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1
884406,USA,07/17/2021 12:00:00 AM,0.020604,0.028230,0.015006,0.0,biweekly,08/03/2021 12:00:00 AM,0,0,...,0,0,0,0,0,0,0,0,0,1

In [28]:
base_date = pa.to_datetime(data['week_ending']).min()

In [31]:
data['Days_Since_min'] = (pa.to_datetime(data['week_ending'])-base_date).dt.days